version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    depends_on:
      - app
    container_name: app_nginx
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    container_name: app
    depends_on:
      - db
  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=gxldmane
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=tenders
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tender
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8101:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: app_db

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local
